apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentgateway
  namespace: agentops
  annotations:
    iam.gke.io/gcp-service-account: agentgateway@agentops-open-course.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: agentops
  annotations:
    iam.gke.io/gcp-service-account: mlflow@agentops-open-course.iam.gserviceaccount.com
