apiVersion: v1
kind: Namespace
metadata:
  name: agentops
  labels:
    app.kubernetes.io/part-of: agentops-open-course
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
