#!/usr/bin/env bash

# Regenerate data/captures.yaml — the derived figures every course capture quotes.
#
#     ./scripts/generate-captures.sh
#
# Why a generated manifest rather than a live check: suite totals and per-package
# coverage percentages cannot be derived without running the suites, and `check:docs`
# runs before `test` in both CI and lefthook. So the numbers are captured once by a
# maintainer, committed, and then `tools/internal/conventions` requires every
# `DONE … tests` line and every coverage figure under content/ to match them. This
# mirrors the `config:generate` / `check:env-example` pair the repository already has.

lib_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib.sh
source "${lib_dir}/lib.sh"

repository_root="$(cd -- "${lib_dir}/.." && pwd)"
output="${repository_root}/data/captures.yaml"

work_dir="$(mktemp -d)"
trap 'rm -rf -- "${work_dir}"' EXIT

# `DONE 1806 tests, 1 skipped in 33.967s` — gotestsum's summary line. The skip count is
# absent when nothing skipped, which is why it is optional here and defaults to zero.
read_suite() {
	local module="$1" log_file="$2" done_line tests skipped

	done_line="$(grep -E '^DONE [0-9]+ tests' "${log_file}" | tail -n 1)" ||
		fail "no gotestsum summary in the ${module} suite output"
	tests="$(sed -E 's/^DONE ([0-9]+) tests.*/\1/' <<<"${done_line}")"
	skipped="$(sed -nE 's/^DONE [0-9]+ tests, ([0-9]+) skipped.*/\1/p' <<<"${done_line}")"
	printf '%s %s\n' "${tests}" "${skipped:-0}"
}

for module in "agents/go" evals tools; do
	log "running the ${module} suite"
	(cd "${repository_root}/${module}" && mise run test) \
		>"${work_dir}/${module//\//-}.log" 2>&1 ||
		fail "the ${module} suite failed; fix it before regenerating the capture manifest"
done

{
	cat <<-'HEADER'
		# Generated by `mise run docs:captures`. Do not edit by hand.
		#
		# Every `DONE <n> tests` line and every per-package coverage figure quoted in a
		# content/ capture is checked against this file by tools/internal/conventions
		# (checkDerivedFigures), so a suite that gains a test fails `mise run check:docs`
		# until the manifest and the pages it backs are regenerated together.
		suites:
	HEADER
	for module in "agents/go" evals tools; do
		summary="$(read_suite "${module}" "${work_dir}/${module//\//-}.log")"
		read -r tests skipped <<<"${summary}"
		printf '  "%s":\n    tests: %s\n    skipped: %s\n' "${module}" "${tests}" "${skipped}"
	done
	printf 'coverage:\n'
	# `  ok      84.2%  agents/go/a2aserver` — check-coverage.sh's report, already sorted
	# by package. Only agents/go is recorded: it is the only module whose per-package
	# numbers course pages quote.
	sed -nE 's/^ *(ok|BELOW) +([0-9]+\.[0-9]+)% +(agents\/go\/.*)$/  "\3": \2/p' \
		"${work_dir}/agents-go.log"
} >"${output}"

log "wrote ${output#"${repository_root}/"}"
